### ISSUE TITLE
How to generate those *.csv and *.tsv files?

### ISSUE THREAD

**Issue by FriedaSmith** [dgd45125/LPPxLDDxCN-EN#1]
Hello. How to generate those ***.csv** and ***.tsv** files? such as `annotaion_CN_lppCN_prosody.csv`, `lpp_CN_word_surprisal_gpt.csv`, `COMPLEXITIES__ch_9apr2022.csv`, `*_f0.csv`, `*_freq.csv`, `*_RMS.csv`, `disc_proj_en_10jan2022.csv`,` COMPLEXITIES__en_9apr2022.csv`, and `Prince_gpt2.tsv`

Can you upload the code that generates ***.csv** and ***.tsv** files?

**Comment by dgd45125** [comment]
Hello,

I have added some files and updated the README.

Chinese:

  - `prepare_regressors/cn/annotaion_CN_lppCN_prosody.csv`comes from the <a href="https://openneuro.org/datasets/ds003643/versions/2.0.1">Le Petit Prince OpenNEURO repository</a>.
  - `prepare_regressors/cn/lpp_CN_word_surprisal_gpt2.csv` comes from the `prepare_regressors/cn/lpp_gpt2_CN_surprisal.py` script which uses `prepare_regressors/cn/lpp_CN_new_sentence.csv` as the input chinese text and `prepare_regressors/cn/lppCN_word_information_sent_info.csv` for word segmentation.
  - The word-by-word syntactic complexity metric and long-distance dependency annotations from `prepare_regressors/cn/COMPLEXITIES__ch_9apr2022.csv` were created via Deepmind-internal code which cannot be released. The process, however, is described in the paper.

English:

  - `prepare_regressors/en/*_f0.csv`, `prepare_regressors/en/*_freq.csv`, and `prepare_regressors/en/*_RMS.csv` are chopped up spreadsheets from the annotations provided in the <a href="https://openneuro.org/datasets/ds003643/versions/2.0.1">Le Petit Prince OpenNEURO repository</a>.
  - `prepare_regressors/en/Prince_gpt2.tsv` comes from feeding `prepare_regressors/en/Prince.txt` into <a href="https://cpllab.github.io/lm-zoo/">lm-zoo</a> and getting the GPT2 surprisal values.
  - The word-by-word syntactic complexity metric from `prepare_regressors/en/disc_proj_en_10jan2022.csv` and the long-distance dependency annotations from `prepare_regressors/en/COMPLEXITIES__en_9apr2022.csv` were created via Deepmind-internal code which cannot be released. The process, however, is described in the paper.

**Comment by FriedaSmith** [comment]
Thank you very much indeed!
